// Generated by Lintel conformance/sync-presets.mjs. Do not edit.
inline std::span<const LinkTooltipPreset> GetLinkTooltipPresets() noexcept
{
    static const LinkTooltipPreset presets[] = {
        { L"jira-issue-keys", L"Jira: Issue keys in output, like CAB-8209", L"Turns a bare issue key printed by a build or a commit message into a hoverable link", Model::HyperlinkMatchKind::Text, {  }, L"\\b(?<key>[A-Z][A-Z0-9]{1,9}-\\d{1,7})\\b", Model::HyperlinkFileTypeGroup::None, {  }, L"jira", true, { L"Jira: Issue keys in output (Text)" } },
        { L"jira-issue-links", L"Jira: Issue links", L"Jira issue URLs, the /browse/ form", Model::HyperlinkMatchKind::Link, {  }, L"^https?://[^/]+/browse/(?<key>[A-Z][A-Z0-9]+-\\d+)", Model::HyperlinkFileTypeGroup::None, {  }, L"jira", true, { L"Jira: Issue links (URL)" } },
        { L"github-pull-requests", L"GitHub: Pull request links", L"GitHub pull request URLs", Model::HyperlinkMatchKind::Link, {  }, L"^https://github\\.com/(?<owner>[^/]+)/(?<repo>[^/]+)/(?<ispull>pull)/(?<number>\\d+)", Model::HyperlinkFileTypeGroup::None, {  }, L"github", true, { L"GitHub: Pull requests & issues (URL)" } },
        { L"github-issues", L"GitHub: Issue links", L"GitHub issue URLs", Model::HyperlinkMatchKind::Link, {  }, L"^https://github\\.com/(?<owner>[^/]+)/(?<repo>[^/]+)/(?<isissue>issues)/(?<number>\\d+)", Model::HyperlinkFileTypeGroup::None, {  }, L"github", true, { L"GitHub: Pull requests & issues (URL)" } },
        { L"github-commits", L"GitHub: Commit links", L"GitHub commit URLs", Model::HyperlinkMatchKind::Link, {  }, L"^https://github\\.com/(?<owner>[^/]+)/(?<repo>[^/]+)/commit/(?<sha>[0-9a-f]{7,40})", Model::HyperlinkFileTypeGroup::None, {  }, L"github", true, { L"GitHub: Commits (URL)" } },
        { L"github-repo-number", L"GitHub: GitHub pull requests and issues (repo#number)", L"Matches repo#number in output and resolves it against the candidate owners", Model::HyperlinkMatchKind::Text, {  }, L"^(?<repo>[A-Za-z0-9_.-]+)#(?<number>\\d+)", Model::HyperlinkFileTypeGroup::None, {  }, L"github", true, { L"GitHub: Pull requests & issues (repo#number)" } },
        { L"slack-messages", L"Slack: Message links", L"Slack permalinks, including a link into a thread", Model::HyperlinkMatchKind::Link, {  }, L"^https://(?<workspace>[a-zA-Z0-9_.-]+)\\.slack\\.com/archives/(?<channel>[A-Z0-9]+)/p(?<tsSeconds>\\d{10})(?<tsMicros>\\d{6})(?:\\?thread_ts=(?<thread>\\d+\\.\\d+))?", Model::HyperlinkFileTypeGroup::None, {  }, L"slack", true, { L"Slack: Message links (URL)" } },
        { L"stith-session-uris", L"Stith: Session links", L"stith:// links to an agent session", Model::HyperlinkMatchKind::Link, {  }, L"^stith://session/(?<id>[A-Za-z0-9-]{4,64})", Model::HyperlinkFileTypeGroup::None, {  }, L"stith", true, { L"Stith: Agent session links" } },
        { L"stith-web-links", L"Stith: Web links", L"Links to a session on the stith web UI", Model::HyperlinkMatchKind::Link, {  }, L"^https?://[^/]+/(?:s|agent|sessions|embed/s)/(?<id>[A-Za-z0-9-]{4,64})", Model::HyperlinkFileTypeGroup::None, {  }, L"stith", true, { L"Stith: Agent session links" } },
        { L"stith-session-ids", L"Stith: Agent session ids printed bare, with no scheme and no link around them", L"A bare session id printed with no scheme and no link around it, which is how one usually appears", Model::HyperlinkMatchKind::Text, {  }, L"\\b(?<id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\b", Model::HyperlinkFileTypeGroup::None, {  }, L"stith", true, { L"Stith: Agent session ids (Text)" } },
        { L"shefrd-pane-ids", L"shefrd: Multiplexer pane ids printed bare, like w1N:p39", L"A multiplexer pane address like w1N:p39; opening one focuses that pane", Model::HyperlinkMatchKind::Text, {  }, L"\\b(?<pane>w[123456789ABCDEFGHJKMNPQRSTVWXYZ0]+:p[123456789ABCDEFGHJKMNPQRSTVWXYZ0]+)\\b", Model::HyperlinkFileTypeGroup::None, {  }, L"shefrd", true, { L"shefrd: Pane ids in output (Text)" } },
        { L"git-commit-hashes", L"Git: Commit hashes in output", L"Abbreviated or full hashes printed by git -- hoverable, and a place to hang a custom action", Model::HyperlinkMatchKind::Text, {  }, L"\\b(?=[0-9a-f]*[a-f])[0-9a-f]{7,40}\\b", Model::HyperlinkFileTypeGroup::None, {  }, L"", false, { L"Git: Commit hashes in output (Text)" } },
        { L"media-files", L"Media: Images, audio and video", L"Links and paths that resolve to a media file", Model::HyperlinkMatchKind::Link, { L"file", L"http", L"https" }, L"", Model::HyperlinkFileTypeGroup::Media, {  }, L"", true, { L"Media: Images, audio & video" } },
        { L"source-code-files", L"Source code files", L"Local paths to a source file", Model::HyperlinkMatchKind::Link, { L"file" }, L"", Model::HyperlinkFileTypeGroup::SourceCode, {  }, L"", true, {  } },
        { L"text-files", L"Text files", L"Local text, Markdown, log and configuration files", Model::HyperlinkMatchKind::Link, { L"file" }, L"", Model::HyperlinkFileTypeGroup::None, { L"txt", L"md", L"log", L"json", L"yaml", L"yml", L"toml", L"ini", L"csv", L"tsv" }, L"", true, {  } },
        { L"pdf-files", L"PDF files", L"Local PDF documents", Model::HyperlinkMatchKind::Link, { L"file" }, L"", Model::HyperlinkFileTypeGroup::None, { L"pdf" }, L"", true, {  } },
        { L"office-document-files", L"Office documents", L"Local Word, Excel and PowerPoint content", Model::HyperlinkMatchKind::Link, { L"file" }, L"", Model::HyperlinkFileTypeGroup::None, { L"docx", L"xlsx", L"pptx" }, L"", true, {  } },
        { L"unblocked-task-ids", L"Unblocked Code: Coding task IDs in output", L"Open Unblocked Code coding-task details", Model::HyperlinkMatchKind::Text, {  }, L"\\b(?<task>UNB-\\d+)\\b", Model::HyperlinkFileTypeGroup::None, {  }, L"unblocked", true, {  } },
        { L"unblocked-task-links", L"Unblocked Code: Coding task details links", L"Open Unblocked Code coding-task details", Model::HyperlinkMatchKind::Link, {  }, L"^https://getunblocked\\.com/dashboard/team/current/coding-task/(?<task>UNB-\\d+)(?:[?#].*)?$", Model::HyperlinkFileTypeGroup::None, {  }, L"unblocked", true, {  } },
    };
    return presets;
}

inline std::wstring_view GetLinkTooltipPresetSample(std::wstring_view id) noexcept
{
    if (id == L"jira-issue-keys") return L"Deployed CAB-8209 to staging";
    if (id == L"jira-issue-links") return L"https://example.atlassian.net/browse/CAB-8209";
    if (id == L"github-pull-requests") return L"https://github.com/aylith-labs/lintel/pull/12";
    if (id == L"github-issues") return L"https://github.com/aylith-labs/lintel/issues/12";
    if (id == L"github-commits") return L"https://github.com/aylith-labs/lintel/commit/c79ccc1f0a7d4e2b1c3f5a6d8e9b0c1d2e3f4a5b";
    if (id == L"github-repo-number") return L"See terminal#18920 for the details";
    if (id == L"slack-messages") return L"https://myteam.slack.com/archives/C01234ABCD/p1712345678000100";
    if (id == L"stith-session-uris") return L"stith://session/1a2b3c4d-5e6f";
    if (id == L"stith-web-links") return L"https://stith.lvh.me/agent/1a2b3c4d-5e6f";
    if (id == L"stith-session-ids") return L"Resuming ce786f3f-6fdc-4165-b9bd-20ff858844db";
    if (id == L"shefrd-pane-ids") return L"it also names the pane, w1N:p39, if you want to watch it work";
    if (id == L"git-commit-hashes") return L"46100068 Record what the Settings crash actually was";
    if (id == L"media-files") return L"/home/steve/captures/screenshot.png";
    if (id == L"source-code-files") return L"/home/steve/projects/lintel/example.ts";
    if (id == L"text-files") return L"/home/steve/notes.md";
    if (id == L"pdf-files") return L"/home/steve/report.pdf";
    if (id == L"office-document-files") return L"/home/steve/report.docx";
    if (id == L"unblocked-task-ids") return L"UNB-123";
    if (id == L"unblocked-task-links") return L"https://getunblocked.com/dashboard/team/current/coding-task/UNB-123";
    return {};
}
