// Generated by Lintel conformance/sync-file-types.mjs. Do not edit.
#pragma once
#include <algorithm>
#include <cwctype>
#include <string>
#include <string_view>
namespace Lintel
{
    struct FileType { std::wstring_view id, name, extensions, filenames, language, groups, icon; };
    inline constexpr FileType FileTypes[] = {
        { L"csharp", L"C#", L"|cs|", L"||", L"csharp", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/csharp.png" },
        { L"typescript", L"TypeScript", L"|ts|tsx|mts|cts|", L"||", L"typescript", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/typescript.png" },
        { L"javascript", L"JavaScript", L"|js|jsx|mjs|cjs|", L"||", L"javascript", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/javascript.png" },
        { L"cpp", L"C++", L"|cpp|cc|cxx|hpp|hh|hxx|", L"||", L"cpp", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/cpp.png" },
        { L"c", L"C", L"|c|h|", L"||", L"c", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/c.png" },
        { L"python", L"Python", L"|py|pyi|pyw|", L"||", L"python", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/python.png" },
        { L"rust", L"Rust", L"|rs|", L"||", L"rust", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/rust.png" },
        { L"go", L"Go", L"|go|", L"||", L"go", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/go.png" },
        { L"java", L"Java", L"|java|", L"||", L"java", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/java.png" },
        { L"ruby", L"Ruby", L"|rb|rake|", L"||", L"ruby", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/ruby.png" },
        { L"powershell", L"PowerShell", L"|ps1|psm1|psd1|", L"||", L"powershell", L"|sourceCode|executable|", L"ms-appx:///IntegrationIcons/files/powershell.png" },
        { L"shell", L"Shell", L"|sh|bash|zsh|fish|", L"||", L"bash", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/shell.png" },
        { L"kotlin", L"Kotlin", L"|kt|kts|", L"||", L"kotlin", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/kotlin.png" },
        { L"swift", L"Swift", L"|swift|", L"||", L"swift", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/swift.png" },
        { L"php", L"PHP", L"|php|", L"||", L"php", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/php.png" },
        { L"sql", L"SQL", L"|sql|", L"||", L"sql", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/sql.png" },
        { L"css", L"CSS", L"|css|scss|sass|less|", L"||", L"css", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/css.png" },
        { L"html", L"HTML", L"|html|htm|", L"||", L"xml", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/html.png" },
        { L"markdown", L"Markdown", L"|md|markdown|mdown|", L"||", L"markdown", L"|document|", L"ms-appx:///IntegrationIcons/files/markdown.png" },
        { L"text", L"Plain text", L"|txt|log|", L"||", L"", L"|document|", L"ms-appx:///IntegrationIcons/files/text.png" },
        { L"json", L"JSON", L"|json|jsonc|", L"||", L"json", L"||", L"ms-appx:///IntegrationIcons/files/json.png" },
        { L"yaml", L"YAML", L"|yaml|yml|", L"||", L"yaml", L"||", L"ms-appx:///IntegrationIcons/files/yaml.png" },
        { L"toml", L"TOML", L"|toml|", L"||", L"toml", L"||", L"ms-appx:///IntegrationIcons/files/toml.png" },
        { L"ini", L"INI", L"|ini|cfg|conf|", L"||", L"ini", L"||", L"ms-appx:///IntegrationIcons/files/ini.png" },
        { L"xml", L"XML", L"|xml|xaml|csproj|", L"||", L"xml", L"||", L"ms-appx:///IntegrationIcons/files/xml.png" },
        { L"csv", L"CSV", L"|csv|tsv|", L"||", L"", L"||", L"ms-appx:///IntegrationIcons/files/csv.png" },
        { L"image", L"Image", L"|png|jpg|jpeg|gif|bmp|webp|svg|ico|tif|tiff|", L"||", L"", L"|image|media|", L"ms-appx:///IntegrationIcons/files/image.png" },
        { L"video", L"Video", L"|mp4|mkv|webm|mov|avi|", L"||", L"", L"|video|media|", L"ms-appx:///IntegrationIcons/files/video.png" },
        { L"audio", L"Audio", L"|mp3|wav|flac|ogg|m4a|", L"||", L"", L"|audio|media|", L"ms-appx:///IntegrationIcons/files/audio.png" },
        { L"pdf", L"PDF document", L"|pdf|", L"||", L"", L"|document|", L"ms-appx:///IntegrationIcons/files/pdf.png" },
        { L"word", L"Word document", L"|docx|doc|", L"||", L"", L"|document|", L"ms-appx:///IntegrationIcons/files/word.png" },
        { L"excel", L"Excel workbook", L"|xlsx|xls|", L"||", L"", L"|document|", L"ms-appx:///IntegrationIcons/files/excel.png" },
        { L"powerpoint", L"PowerPoint presentation", L"|pptx|ppt|", L"||", L"", L"|document|", L"ms-appx:///IntegrationIcons/files/powerpoint.png" },
        { L"archive", L"Archive", L"|zip|7z|rar|tar|gz|bz2|xz|tgz|", L"||", L"", L"|archive|", L"ms-appx:///IntegrationIcons/files/archive.png" },
        { L"executable", L"Executable", L"|exe|msi|bat|cmd|", L"||", L"", L"|executable|", L"ms-appx:///IntegrationIcons/files/executable.png" },
        { L"dockerfile", L"Dockerfile", L"||", L"|dockerfile|containerfile|", L"dockerfile", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/dockerfile.png" },
        { L"makefile", L"Makefile", L"||", L"|makefile|gnumakefile|", L"makefile", L"|sourceCode|", L"ms-appx:///IntegrationIcons/files/makefile.png" },
        { L"file", L"File", L"||", L"||", L"", L"||", L"ms-appx:///IntegrationIcons/files/file.png" },
    };
    inline std::wstring Lower(std::wstring_view value) { std::wstring out{ value }; std::transform(out.begin(),out.end(),out.begin(),[](wchar_t c){ return static_cast<wchar_t>(std::towlower(c)); }); return out; }
    inline std::wstring ExtensionOf(std::wstring_view target)
    {
        if (target.find(L"://") != target.npos) target = target.substr(0, target.find_first_of(L"?#"));
        const auto slash = target.find_last_of(L"/\\");
        const auto name = target.substr(slash == target.npos ? 0 : slash + 1);
        const auto dot = name.find_last_of(L'.');
        return dot == name.npos || dot == 0 ? std::wstring{} : Lower(name.substr(dot + 1));
    }
    inline bool Contains(std::wstring_view list, std::wstring_view value) { return !value.empty() && list.find(L"|" + std::wstring{value} + L"|") != list.npos; }
    inline const FileType& FindFileType(std::wstring_view path)
    {
        const auto extension = ExtensionOf(path);
        const auto name = Lower(path.substr(path.find_last_of(L"/\\") + 1));
        for (const auto& type : FileTypes) if (Contains(type.extensions, extension) || Contains(type.filenames, name)) return type;
        return FileTypes[std::size(FileTypes) - 1];
    }
    inline bool GroupContains(std::wstring_view group, std::wstring_view extension)
    {
        const auto lower = Lower(extension);
        for (const auto& type : FileTypes) if (Contains(type.extensions, lower) && Contains(type.groups, group)) return true;
        return false;
    }
}
