// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass AboutDialog : Windows.UI.Xaml.Controls.ContentDialog, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        AboutDialog();

        String ApplicationDisplayName { get; };
        String ApplicationVersion { get; };
        String BuildCommit { get; };
        String BuildBranch { get; };
        String BuildTime { get; };
        String BuildExePath { get; };

        Boolean CheckingForUpdates { get; };
        Boolean UpdatesAvailable { get; };
        String UpdateStatusText { get; };
    }
}
